name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH="$PATH:/root/.nvm/versions/node/v22.2.0/bin/"
            cd /var/apps/green-summary-202425
            git pull
            pnpm install
            pnpm build
            pm2 restart summary-frontend & pm2 restart summary-backend && kill $!
